# Generated by Django 5.0.1 on 2024-01-30 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deceased_first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('deceased_last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('deceased_middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('deceased_birth_date', models.DateField(blank=True, null=True)),
                ('deceased_death_date', models.DateField(blank=True, null=True)),
                ('epitaph', models.TextField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='photo/avatars/')),
                ('biography', models.TextField(blank=True, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=255, null=True)),
                ('place_of_death', models.CharField(blank=True, max_length=255, null=True)),
                ('nationality', models.CharField(blank=True, max_length=255, null=True)),
                ('spouse', models.CharField(blank=True, max_length=255, null=True)),
                ('profession', models.CharField(blank=True, max_length=255, null=True)),
                ('photo_gallery', models.JSONField(blank=True, null=True)),
                ('video_gallery', models.JSONField(blank=True, null=True)),
                ('audio_gallery', models.JSONField(blank=True, null=True)),
                ('guestbook', models.JSONField(blank=True, null=True)),
                ('significant_places', models.JSONField(blank=True, null=True)),
                ('creative_works', models.JSONField(blank=True, null=True)),
                ('awards', models.JSONField(blank=True, null=True)),
                ('education', models.JSONField(blank=True, null=True)),
                ('family_composition', models.JSONField(blank=True, null=True)),
                ('hobbies', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_pages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.CharField(choices=[('free', 'Бесплатная'), ('basic', 'Базовая'), ('premium', 'Премиум'), ('vip', 'VIP')], default='free', max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_photos', models.PositiveIntegerField()),
                ('max_videos', models.PositiveIntegerField()),
                ('max_audio', models.PositiveIntegerField()),
                ('max_links', models.PositiveIntegerField()),
                ('max_profiles', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
    ]
