# Generated by Django 5.0.1 on 2024-01-23 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deceased_first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('deceased_last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('deceased_middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('deceased_birth_date', models.DateField(blank=True, null=True)),
                ('deceased_death_date', models.DateField(blank=True, null=True)),
                ('epitaph', models.TextField(blank=True, null=True)),
                ('biography', models.TextField(blank=True, null=True)),
                ('page_avatar', models.ImageField(blank=True, null=True, upload_to='page_avatar/')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_photos', models.PositiveIntegerField()),
                ('max_videos', models.PositiveIntegerField()),
                ('max_audio', models.PositiveIntegerField()),
                ('max_links', models.PositiveIntegerField()),
                ('allow_reviews', models.BooleanField(default=False)),
                ('allow_extended_biography', models.BooleanField(default=False)),
                ('allow_specialist_service', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ExtendedMemoryPageInfo',
            fields=[
                ('memory_page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.memorypage')),
                ('place_of_birth', models.CharField(blank=True, max_length=255, null=True)),
                ('place_of_death', models.CharField(blank=True, max_length=255, null=True)),
                ('spouse', models.CharField(blank=True, max_length=255, null=True)),
                ('nationality', models.CharField(blank=True, max_length=255, null=True)),
                ('occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('significant_places', models.TextField(blank=True, null=True)),
                ('life_milestones', models.TextField(blank=True, null=True)),
                ('personal_anecdotes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.subscription')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HobbyInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('memory_page_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hobbies_interests', to='users.extendedmemorypageinfo')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('relationship', models.CharField(choices=[('parent', 'parent'), ('sibling', 'sibling'), ('child', 'child')], max_length=255)),
                ('memory_page_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='users.extendedmemorypageinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(blank=True, max_length=255, null=True)),
                ('degree', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('years_attended', models.CharField(blank=True, max_length=255, null=True)),
                ('memory_page_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='users.extendedmemorypageinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateField(blank=True, null=True)),
                ('memory_page_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='users.extendedmemorypageinfo')),
            ],
        ),
    ]
