# Generated by Django 5.0.1 on 2024-01-25 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedMemoryPageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_of_birth', models.CharField(blank=True, max_length=255, null=True)),
                ('place_of_death', models.CharField(blank=True, max_length=255, null=True)),
                ('spouse', models.CharField(blank=True, max_length=255, null=True)),
                ('nationality', models.CharField(blank=True, max_length=255, null=True)),
                ('occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('significant_places', models.TextField(blank=True, null=True)),
                ('life_milestones', models.TextField(blank=True, null=True)),
                ('personal_anecdotes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Расширенная информация',
                'verbose_name_plural': 'Расширенная информация',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_photos', models.PositiveIntegerField()),
                ('max_videos', models.PositiveIntegerField()),
                ('max_audio', models.PositiveIntegerField()),
                ('max_links', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(blank=True, max_length=255, null=True)),
                ('degree', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('years_attended', models.CharField(blank=True, max_length=255, null=True)),
                ('memory_page_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='users.extendedmemorypageinfo')),
            ],
            options={
                'verbose_name': 'Образование',
                'verbose_name_plural': 'Образование',
            },
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateField(blank=True, null=True)),
                ('memory_page_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='users.extendedmemorypageinfo')),
            ],
            options={
                'verbose_name': 'Награда',
                'verbose_name_plural': 'Награды',
            },
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('relationship', models.CharField(choices=[('parent', 'Родители'), ('sibling', 'Сестры/Братья'), ('child', 'Дети')], max_length=255)),
                ('memory_page_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='users.extendedmemorypageinfo', verbose_name='Страница памяти')),
            ],
            options={
                'verbose_name': 'Член семьи',
                'verbose_name_plural': 'Члены семьи',
            },
        ),
        migrations.CreateModel(
            name='HobbyInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('memory_page_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hobbies_interests', to='users.extendedmemorypageinfo')),
            ],
            options={
                'verbose_name': 'Хобби и интересы',
                'verbose_name_plural': 'Хобби и интересы',
            },
        ),
        migrations.CreateModel(
            name='MemoryPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deceased_first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('deceased_last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('deceased_middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('deceased_birth_date', models.DateField(blank=True, null=True)),
                ('deceased_death_date', models.DateField(blank=True, null=True)),
                ('epitaph', models.TextField(blank=True, null=True)),
                ('biography', models.TextField(blank=True, null=True)),
                ('page_avatar', models.ImageField(blank=True, null=True, upload_to='page_avatar/')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Страница памяти',
                'verbose_name_plural': 'Страницы памяти',
            },
        ),
        migrations.AddField(
            model_name='extendedmemorypageinfo',
            name='memory_page',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.memorypage', verbose_name='Страница памяти'),
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_add_photos', models.BooleanField(default=False, verbose_name='Разрешить добавлять фотографий')),
                ('can_add_videos', models.BooleanField(default=False, verbose_name='Разрешить добавлять видео')),
                ('can_add_audio', models.BooleanField(default=False, verbose_name='Разрешить добавлять аудио')),
                ('can_add_links', models.BooleanField(default=False, verbose_name='Разрешить добавлять ссылки')),
                ('can_add_reviews', models.BooleanField(default=False, verbose_name='Разрешить добавлять отзывы')),
                ('can_add_place_of_birth', models.BooleanField(default=False, verbose_name='Разрешить добавлять место рождения')),
                ('cann_add_place_of_death', models.BooleanField(default=False, verbose_name='Разрешить добавлять место смерти')),
                ('can_add_spouse', models.BooleanField(default=False, verbose_name='Разрешить добавлять супруга')),
                ('can_add_nationality', models.BooleanField(default=False, verbose_name='Разрешить добавлять национальность')),
                ('can_add_occupation', models.BooleanField(default=False, verbose_name='Разрешить добавлять профессию')),
                ('can_add_awards', models.BooleanField(default=False, verbose_name='Разрешить добавлять награды')),
                ('can_add_education', models.BooleanField(default=False, verbose_name='Разрешить добавлять образование')),
                ('can_add_family_members', models.BooleanField(default=False, verbose_name='Разрешить добавлять членов семьи')),
                ('can_add_hobbies_interests', models.BooleanField(default=False, verbose_name='Разрешить добавлять хобби и интересы')),
                ('can_add_life_milestones', models.BooleanField(default=False, verbose_name='Разрешить добавлять вехи жизни')),
                ('can_add_personal_anecdotes', models.BooleanField(default=False, verbose_name='Разрешить добавлять личные анекдоты')),
                ('can_add_significant_places', models.BooleanField(default=False, verbose_name='Разрешить добавлять значимые места')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='users.subscription')),
            ],
            options={
                'verbose_name': 'Разрешение',
                'verbose_name_plural': 'Разрешения',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.subscription')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
