# Generated by Django 5.0.1 on 2024-01-23 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='award',
            options={'verbose_name': 'Награда', 'verbose_name_plural': 'Награды'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'Образование', 'verbose_name_plural': 'Образование'},
        ),
        migrations.AlterModelOptions(
            name='extendedmemorypageinfo',
            options={'verbose_name': 'Расширенная информация', 'verbose_name_plural': 'Расширенная информация'},
        ),
        migrations.AlterModelOptions(
            name='familymember',
            options={'verbose_name': 'Член семьи', 'verbose_name_plural': 'Члены семьи'},
        ),
        migrations.AlterModelOptions(
            name='hobbyinterest',
            options={'verbose_name': 'Хобби и интересы', 'verbose_name_plural': 'Хобби и интересы'},
        ),
        migrations.AlterModelOptions(
            name='memorypage',
            options={'verbose_name': 'Страница памяти', 'verbose_name_plural': 'Страницы памяти'},
        ),
        migrations.AlterModelOptions(
            name='permissions',
            options={'verbose_name': 'Разрешение', 'verbose_name_plural': 'Разрешения'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='allow_extended_biography',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='allow_reviews',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='allow_specialist_service',
        ),
        migrations.AlterField(
            model_name='permissions',
            name='can_add_audio',
            field=models.BooleanField(default=False, verbose_name='Разрешить добавлять аудио'),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='can_add_awards',
            field=models.BooleanField(default=False, verbose_name='Разрешить добавлять награды'),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='can_add_education',
            field=models.BooleanField(default=False, verbose_name='Разрешить добавлять образование'),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='can_add_family_members',
            field=models.BooleanField(default=False, verbose_name='Разрешить добавлять членов семьи'),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='can_add_hobbies_interests',
            field=models.BooleanField(default=False, verbose_name='Разрешить добавлять хобби и интересы'),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='can_add_life_milestones',
            field=models.BooleanField(default=False, verbose_name='Разрешить добавлять вехи жизни'),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='can_add_links',
            field=models.BooleanField(default=False, verbose_name='Разрешить добавлять ссылки'),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='can_add_nationality',
            field=models.BooleanField(default=False, verbose_name='Разрешить добавлять национальность'),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='can_add_occupation',
            field=models.BooleanField(default=False, verbose_name='Разрешить добавлять профессию'),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='can_add_personal_anecdotes',
            field=models.BooleanField(default=False, verbose_name='Разрешить добавлять личные анекдоты'),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='can_add_photos',
            field=models.BooleanField(default=False, verbose_name='Разрешить добавлять фотографий'),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='can_add_place_of_birth',
            field=models.BooleanField(default=False, verbose_name='Разрешить добавлять место рождения'),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='can_add_reviews',
            field=models.BooleanField(default=False, verbose_name='Разрешить добавлять отзывы'),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='can_add_significant_places',
            field=models.BooleanField(default=False, verbose_name='Разрешить добавлять значимые места'),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='can_add_spouse',
            field=models.BooleanField(default=False, verbose_name='Разрешить добавлять супруга'),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='can_add_videos',
            field=models.BooleanField(default=False, verbose_name='Разрешить добавлять видео'),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='cann_add_place_of_death',
            field=models.BooleanField(default=False, verbose_name='Разрешить добавлять место смерти'),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='users.subscription'),
        ),
    ]
